// <auto-generated />
namespace SampleParser.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M01));
        
        string IMigrationMetadata.Id
        {
            get { return "202007240722272_M01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
